#!/usr/bin/env python3
# Updater is a easy Linux apt downloader
# Created by Melih Can
# 08/09/2021
# Gnu General Public License 3.0
# Version 1.0

from colorama import Fore
from datetime import datetime
import os
import sys
import pyfiglet
import time

colorama.init()

banner = pyfiglet.figlet_format("Updater")
options = '''
  #---------------[_][o][x]
  # 1. Package Update     #
  #-----------------------#
  # 2. Package Upgrade    #
  #-----------------------#
  # 3. Package Install    #
  #-----------------------#
  # 4. Package Uninstall  #
  #-----------------------#
  # 5. Package Autoremove #
  #-----------------------#
  # 6. Package Fix        #
  #-----------------------#
  # 7. About              #
  #-----------------------#
  # 8. Exit               #
  #------Updater----------#
'''

while True:
    print(Fore.LIGHTBLUE_EX)
    print(banner)
    print("-"*30)
    print(datetime.now().strftime("%d/%m/%Y %H:%M:%S"))
    print("-"*30)
    print(Fore.LIGHTWHITE_EX)
    print("Updater is a easy Linux apt downloader...")
    print(Fore.LIGHTGREEN_EX)
    print(options)
    print(Fore.LIGHTWHITE_EX)

    try:
        user = input("Select the operation: ")

    except KeyboardInterrupt:
        os.system("clear")
        print("Exitting Program")
        sys.exit(3)

    if user == '1':
        os.system("sudo apt-get update")
        print(Fore.LIGHTGREEN_EX)
        input("Operation Complete...")
        os.system("clear")

    elif user == '2':
        os.system("sudo apt-get upgrade")
        print(Fore.LIGHTGREEN_EX)
        input("Operation Complete...")
        os.system("clear")

    elif user == '3':
        try:
            package = input("Enter the package name: ")
            command = f"sudo apt-get install {package} -y"
            os.system(command)
            print(Fore.LIGHTGREEN_EX)
            input("Operation Complete...")
            os.system("clear")

        except KeyboardInterrupt:
            print("Exitting Program")
            os.system("clear")

    elif user == '4':
        try:
            package = input("Enter the package name: ")
            command = f"sudo apt-get remove {package} -y"
            os.system(command)
            print(Fore.LIGHTGREEN_EX)
            input("Operation Complete...")
            os.system("clear")

        except KeyboardInterrupt:
            print("Exitting Program")
            os.system("clear")

    elif user == '5':
        os.system("sudo apt-get autoremove -y")
        print(Fore.LIGHTGREEN_EX)
        input("Operation Complete...")
        os.system("clear")

    elif user == '6':
        os.system("sudo apt-get install --fix-missing")
        print(Fore.LIGHTGREEN_EX)
        input("Operation Complete...")
        os.system("clear")

    elif user == '7':
        os.system("clear")
        print(Fore.LIGHTGREEN_EX)
        print("Updater is a easy Linux apt downloader\n")
        print("Created by Melih Can\n")
        print("08/09/2021\n")
        print("Gnu General Public License 3.0\n")
        print("Version 1.0\n")
        print("E-mail: Melihcan1376@gmail.com")
        input()
        os.system("clear")

    elif user == '8':
        time.sleep(1)
        print("Reloading...")
        os.system("clear")
        break

    else:
        print(Fore.LIGHTRED_EX)
        print("Error! Your Select Operation Not Found...")
        print("Reloading...")
        time.sleep(3)
        os.system("clear")
