#!/usr/bin/python3
import os
from colorama import Fore
from pyfiglet import figlet_format

banner = figlet_format("Updater")

def get_input(prompt):
    return input(prompt)

actions = {
    '1': 'sudo apt-get update -y',
    '2': 'sudo apt-get upgrade -y',
    '3': lambda: f'sudo apt-get install {get_input("Enter the package name: ")} -y',
    '4': lambda: f'sudo apt-get remove {get_input("Enter the package name: ")} -y',
    '5': 'sudo apt-get autoremove -y',
    '6': 'sudo apt-get install --fix-missing -y',
    '7': '',
    '8': 'exit',
}

options = '''
  #---------------------[_][o][x]
  # 1. Package Update           #
  #-----------------------------#
  # 2. Package Upgrade          #
  #-----------------------------#
  # 3. Package Install          #
  #-----------------------------#
  # 4. Package Uninstall        #
  #-----------------------------#
  # 5. Package Autoremove       #
  #-----------------------------#
  # 6. Package Fix              #
  #-----------------------------#
  # 7. About                    #
  #-----------------------------#
  # 8. Exit                     #
  #-----------------------------#
'''

while True:
    os.system('clear')
    print(Fore.BLUE, end="")
    print(banner)
    print(Fore.LIGHTGREEN_EX,end="")
    print(options)
    print(Fore.LIGHTWHITE_EX,end="")

    user = get_input("Select Options: ")
    command = actions.get(user)
    if command == 'exit':
        break
    
    if command:
        if callable(command):
            command = command()
        os.system(command)
        print(Fore.LIGHTGREEN_EX)
        input("Operation Complete...")
    else:
        print(Fore.LIGHTRED_EX)
        print("Error! Your Select Operation Not Found...")
        input("Enter the return program")
