#!/usr/bin/env python3
# Updater is a easy Linux apt downloader
# Created by Melih Can
# 08/09/2021
# Gnu General Public License 3.0
# Version 1.0

from colorama import Fore
import os
import sys
import pyfiglet


banner = pyfiglet.figlet_format("Updater")
options = '''
  #---------------------[_][o][x]
  # 1. Package Update           #
  #-----------------------------#
  # 2. Package Upgrade          #
  #-----------------------------#
  # 3. Package Install          #
  #-----------------------------#
  # 4. Package Uninstall        #
  #-----------------------------#
  # 5. Package Autoremove       #
  #-----------------------------#
  # 6. Package Fix              #
  #-----------------------------#
  # 7. About                    #
  #-----------------------------#
  # 8. Exit                     #
  #-----------------------------#
'''

while True:
    print(Fore.BLUE, end="")
    print(banner)
    print(Fore.LIGHTGREEN_EX,end="")
    print(options)
    print(Fore.LIGHTWHITE_EX,end="")
    try:
        user = input("Select Options: ")

    except KeyboardInterrupt:
        os.system("clear")
        print("Exitting Program")
        sys.exit(3)

    if user == '1':
        os.system("sudo apt-get update -y")
        print(Fore.LIGHTGREEN_EX)
        input("Operation Complete...")
        os.system("clear")

    elif user == '2':
        os.system("sudo apt-get upgrade -y")
        print(Fore.LIGHTGREEN_EX)
        input("Operation Complete...")
        os.system("clear")

    elif user == '3':
        try:
            package = input("Enter the package name: ")
            command = f"sudo apt-get install {package} -y"
            os.system(command)
            print(Fore.LIGHTGREEN_EX)
            input("Operation Complete...")
            os.system("clear")

        except KeyboardInterrupt:
            print("Exitting Program")
            os.system("clear")

    elif user == '4':
        try:
            package = input("Enter the package name: ")
            command = f"sudo apt-get remove {package} -y"
            os.system(command)
            print(Fore.LIGHTGREEN_EX)
            input("Operation Complete...")
            os.system("clear")

        except KeyboardInterrupt:
            print("Exitting Program")
            os.system("clear")

    elif user == '5':
        os.system("sudo apt-get autoremove -y")
        print(Fore.LIGHTGREEN_EX)
        input("Operation Complete...")
        os.system("clear")

    elif user == '6':
        os.system("sudo apt-get install --fix-missing -y")
        print(Fore.LIGHTGREEN_EX)
        input("Operation Complete...")
        os.system("clear")

    elif user == '7':
        os.system("clear")
        print(banner)
        print(Fore.LIGHTGREEN_EX)
        print("Updater is a easy Linux apt downloader")
        print("-"*40)
        print("Created by Melih Can")
        print("08/09/2021")
        print("Version 1.0")
        print("-"*40)
        print("E-mail: Melihcan1376@gmail.com")
        input()
        os.system("clear")

    elif user == '8':
        os.system("clear")
        break

    else:
        print(Fore.LIGHTRED_EX)
        print("Error! Your Select Operation Not Found...")
        input()
        os.system("clear")
